# Generated by Django 5.0 on 2024-01-06 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0002_chairman_pic_alter_chairman_firstname_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=20)),
                ('lastname', models.CharField(max_length=20)),
                ('contactno', models.CharField(max_length=20, null=True)),
                ('houseno', models.CharField(max_length=8)),
                ('vehicle_details', models.CharField(max_length=20, null=True)),
                ('occupation', models.CharField(max_length=20, null=True)),
                ('no_familymembers', models.CharField(max_length=20, null=True)),
                ('job_address', models.CharField(max_length=20, null=True)),
                ('old_city', models.CharField(max_length=20, null=True)),
                ('blood_grp', models.CharField(max_length=20, null=True)),
                ('birthdate', models.DateField(null=True)),
                ('joining_date', models.DateTimeField(auto_now_add=True)),
                ('pic', models.FileField(default='default.jpeg', upload_to='media/images/')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chairmanapp.user')),
            ],
        ),
    ]
