# Generated by Django 5.0 on 2024-01-24 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chairmanapp', '0004_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='notice',
        ),
    ]
